---
- hosts: servers
  gather_facts: yes
  become: false
  vars: 
    filename: "{{ file_name }}"
  tasks:
  - name: distribution details list
    set_fact: 
      dist_name: "{{ ansible_distribution }}"
      dist_version: "{{ ansible_distribution_version }}"
      dist_major_version: "{{ ansible_distribution_major_version }}"
  - name: print
    shell: echo "HostName,Name,Version,Major Version" > /tmp/reports/{{ filename }}.csv;
    #shell: echo "HostName,Name" > /tmp/reports/server.csv;
    run_once: true
    delegate_to: localhost
  - name: print values
    shell: echo "{{ inventory_hostname }}","{{ dist_name }}","{{ dist_version }}","{{ dist_major_version }}" >> /tmp/reports/{{ filename }}.csv;
    delegate_to: localhost    